## Ordinal numbering encoding or Label Encoding

**Ordinal categorical variables**

Ordinal data is a categorical, statistical data type where the variables have natural, ordered categories and the distances between the categories is not known.
For example:

- Student's grade in an exam (A, B, C or Fail).
- Educational level, with the categories: Elementary school,  High school, College graduate, PhD ranked from 1 to 4.

When the categorical variables are ordinal, the most straightforward best approach is to replace the labels by some ordinal number based on the ranks.

In [38]:
import pandas as pd
import numpy as np
import datetime

In [39]:
# create a variable with dates, and from that extract the weekday
#  create a list of dates with 20 days difference from today
# and then transform it into a datafame
df_base = datetime.datetime.today()
df_base_list= [df_base-datetime.timedelta(days=x) for x in range(0,20)]
df= pd.DataFrame(df_base_list, columns=['days'])

In [40]:
df_base

datetime.datetime(2026, 1, 14, 17, 29, 2, 670495)

In [41]:
df_base_list

[datetime.datetime(2026, 1, 14, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 13, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 12, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 11, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 10, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 9, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 8, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 7, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 6, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 5, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 4, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 3, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 2, 17, 29, 2, 670495),
 datetime.datetime(2026, 1, 1, 17, 29, 2, 670495),
 datetime.datetime(2025, 12, 31, 17, 29, 2, 670495),
 datetime.datetime(2025, 12, 30, 17, 29, 2, 670495),
 datetime.datetime(2025, 12, 29, 17, 29, 2, 670495),
 datetime.datetime(2025, 12, 28, 17, 29, 2, 670495),
 datetime.datetime(2025, 12, 27, 17, 29, 2, 670495),
 datetime.datetime(2025, 12, 26, 17, 29, 2, 670495)]

In [42]:
df

                         days
0  2026-01-14 17:29:02.670495
1  2026-01-13 17:29:02.670495
2  2026-01-12 17:29:02.670495
3  2026-01-11 17:29:02.670495
4  2026-01-10 17:29:02.670495
5  2026-01-09 17:29:02.670495
6  2026-01-08 17:29:02.670495
7  2026-01-07 17:29:02.670495
8  2026-01-06 17:29:02.670495
9  2026-01-05 17:29:02.670495
10 2026-01-04 17:29:02.670495
11 2026-01-03 17:29:02.670495
12 2026-01-02 17:29:02.670495
13 2026-01-01 17:29:02.670495
14 2025-12-31 17:29:02.670495
15 2025-12-30 17:29:02.670495
16 2025-12-29 17:29:02.670495
17 2025-12-28 17:29:02.670495
18 2025-12-27 17:29:02.670495
19 2025-12-26 17:29:02.670495

In [43]:
#extracting week day name
df['day_of_week']= df['days'].dt.day_name()

In [44]:
df

                         days day_of_week
0  2026-01-14 17:29:02.670495   Wednesday
1  2026-01-13 17:29:02.670495     Tuesday
2  2026-01-12 17:29:02.670495      Monday
3  2026-01-11 17:29:02.670495      Sunday
4  2026-01-10 17:29:02.670495    Saturday
5  2026-01-09 17:29:02.670495      Friday
6  2026-01-08 17:29:02.670495    Thursday
7  2026-01-07 17:29:02.670495   Wednesday
8  2026-01-06 17:29:02.670495     Tuesday
9  2026-01-05 17:29:02.670495      Monday
10 2026-01-04 17:29:02.670495      Sunday
11 2026-01-03 17:29:02.670495    Saturday
12 2026-01-02 17:29:02.670495      Friday
13 2026-01-01 17:29:02.670495    Thursday
14 2025-12-31 17:29:02.670495   Wednesday
15 2025-12-30 17:29:02.670495     Tuesday
16 2025-12-29 17:29:02.670495      Monday
17 2025-12-28 17:29:02.670495      Sunday
18 2025-12-27 17:29:02.670495    Saturday
19 2025-12-26 17:29:02.670495      Friday

In [45]:
#engineer categorical variable by ordinal number replacement
weekday_map= {
    'Monday':1,
    'Tuesday':2,
    'Wednesday':3,
    'Thursday':4,
    'Friday':5,
    'Saturday':6,
    'Sunday':7

}
df['day_original']= df.day_of_week.map(weekday_map)
df.head(20)

                         days day_of_week  day_original
0  2026-01-14 17:29:02.670495   Wednesday             3
1  2026-01-13 17:29:02.670495     Tuesday             2
2  2026-01-12 17:29:02.670495      Monday             1
3  2026-01-11 17:29:02.670495      Sunday             7
4  2026-01-10 17:29:02.670495    Saturday             6
5  2026-01-09 17:29:02.670495      Friday             5
6  2026-01-08 17:29:02.670495    Thursday             4
7  2026-01-07 17:29:02.670495   Wednesday             3
8  2026-01-06 17:29:02.670495     Tuesday             2
9  2026-01-05 17:29:02.670495      Monday             1
10 2026-01-04 17:29:02.670495      Sunday             7
11 2026-01-03 17:29:02.670495    Saturday             6
12 2026-01-02 17:29:02.670495      Friday             5
13 2026-01-01 17:29:02.670495    Thursday             4
14 2025-12-31 17:29:02.670495   Wednesday             3
15 2025-12-30 17:29:02.670495     Tuesday             2
16 2025-12-29 17:29:02.670495      Monday             1
17 2025-12-28 17:29:02.670495      Sunday             7
18 2025-12-27 17:29:02.670495    Saturday             6
19 2025-12-26 17:29:02.670495      Friday             5

#### Ordinal Measurement Advantages

Ordinal measurement is normally used for surveys and questionnaires. Statistical analysis is applied to the responses once they are collected to place the people who took the survey into the various categories. The data is then compared to draw inferences and conclusions about the whole surveyed population with regard to the specific variables. The advantage of using ordinal measurement is ease of collation and categorization. If you ask a survey question without providing the variables, the answers are likely to be so diverse they cannot be converted to statistics.

With Respect to Machine Learning

- Keeps the semantical information of the variable (human readable content)
- Straightforward

#### Ordinal Measurement Disadvantages
The same characteristics of ordinal measurement that create its advantages also create certain disadvantages. The responses are often so narrow in relation to the question that they create or magnify bias that is not factored into the survey. For example, on the question about satisfaction with the governor, people might be satisfied with his job performance but upset about a recent sex scandal. The survey question might lead respondents to state their dissatisfaction about the scandal, in spite of satisfaction with his job performance -- but the statistical conclusion will not differentiate.

With Respect to Machine Learning

- Does not add machine learning valuable information